### ISSUE TITLE
Testing Skinchanger Decision Events

### ISSUE THREAD

**Issue by RedArkady** [jj248/RealmsInExile#404]
Skinchangers' decision events are triggered by playing any Woodmen / Valemen holder with the Skinchanger trait (e..g, Grimbeorn).

The events are triggered by activating the "Skinchange" activity, found in the decisions panel.

Play around with them, make sure:

- Triggering the decision costs prestige
- There are cooldowns (3 years)
- There are chains of events
- Events are randomly chosen

The list of events are:
- The Honey Incident
- A Mountain Raid
- A Lost Homeland
- The Carrock
- An Unexpected Arrow

The carrock, since it's a short event, triggers another decision after it - if you decide to go East (it triggers An Unexpected Arrow) or West (it triggers A Mountain Raid).

**Comment by JukeJukestar** [comment]
I tested almost all the event chains and here are my thoughts about them. Overall I think this is a really nice small flavor decision to add some depth to the beornings!

## General notes on event design
- The Skinchanger trait description could feature "Unlocks the Skinchange decision"
- The Skinchanging decision should have "You will loose some stress" in their description, in line with vanilla ones such as "Lash Out", "Seclude Yourself" etc. The stress loss would be applied in the final event where you turn back
- Event choices should factor in character traits to give stress like vanilla ones do.
- Failing a skill check should not give the same reward as succeeding in it. (In these events the only difference is usually a chance to get wounded)


Gameplaywise it could make sense to add a sixth event chain with a higher chance of triggering than the other ones. This one would just be "Patrolled the wilds, nothing special happened" It would give your domain counties a "protected by beasts" modifier that gives a small buff to development growth and a small malus to peasant opinion.
The idea behind this is that this is the "normal" outcome of taking the decision, similar to having an eventless hunt where you just get 150 prestige at the end. This would make players less likely to repeat the event chains over and over.


## Event chain notes
### The Honey Incident
- Instead of having both choices of the initial event give the "honeycomb feast" modifier, the final event should give that effect.
- Opening the door as a shy or reclusive character should give stress like in vanilla
- The event that fires when opening the door should give a small prestige and court grandeur hit (to integrate RC a bit)
- The event that fires when continuing to sleep should not have a flat 33% chance of becoming reclusive, especially since the initial event choice doesnt tell you it has this effect.
- Instead the outcome could be one of the "peasants upset" county modifiers; a negative courtier opinion character modifier or very small chance to gain the reclusive trait, etc.


### A Mountain Raid
- Events need event backgrounds
- Failing Skill challenges should not give the same positive effect as winning them
- Martial and prowess challenges are far too hard, I tested them with Grimbeorn (Excellent 26 martial, excellent 43 prowess) and still had a 38%/ 50% / 44% success chance

### A Lost Homeland
- In its current form this event chain is essentially just a refund of the decision cost with no further benefits
- The learning challenge only affects how high the prestige reward is
- The outcomes should be more interesting, for example winning the learning challenge could give a very small ammount of dynasty renown and the outcomes could have a positive/ negative monthly prestige gain modifier

### An Unexpected Arrow
- Winning the prowess challenge should not wound you
- Prowess challenge is too hard

### The Carrock
- Should not have a flat 100% chance of giving the chosen commander trait, could be nerfed to be around 50% instead

**Comment by RedArkady** [comment]
- Added ""Unlocks the Skinchange decision" to the trait description.

**Comment by RedArkady** [comment]
Implemented a few more of these recommendations. Unlikely to return to it, so closing.
