### ISSUE TITLE
Umbar and Near Harad - more Cadet & bastard houses

### ISSUE THREAD

**Issue by Jermanlordy** [jj248/RealmsInExile#476]
So I was thinking while talking in lore about castamirs usurpation and thought castamir had nobles that supported him and his cause and they probably lost there land after he lost so it would be interesting if they had some bastard houses like the cassimirioni around unlanded in the court of umbar or haruzan

**Comment by Remerod** [comment]
More unlanded houses is always nice. Looking through different fan(like mods) projects and different games to coming up with that stuff is always nice. I think it's pretty ok that say to Feel free to look around for such.

**Comment by Remerod** [comment]
It is always good with more bastard/cadet houses. It would be good if a list of people that needs bastard/cadet houses is made if someone is gonna work on this issue, and for there to be some lore references being made!

**Comment by JukeJukestar** [comment]
Im personally a big fan of having dynasty histories interwoven because it really makes it feel like the constant schemeing didnt begin at game start, but reaches far further back!

It could also be interesting if some of the Umbarean noble dynasties originated from bastards of important (and minor) Gondorian houses, who chose to support Castamir, not just the castamiri line itself
It would maybe even be interesting to have an Umbarean cadet of a gondorian house because the original castamiri supporter was a legitimate second or third son, but that could lead to wonky inheritance

**Comment by Remerod** [comment]
I do like this, and if noone else want to work on this then i could probably find some good lore for this!

Having said that, i do have many balls in the air so this is nothing i would work soon on, this shouldn't be to hard either, just read some stuff from the merp book of the **Kin-Strife**, and double check with @VectorMaximus if the lore from it and the stuff you work on will fit for realms.

I'll move this to non-release critical for now, i do think this have a big chance to be worked on (because everyone loves Umbar)

**Comment by jj248** [comment]
I suggest we push this to v4.  We already have enough to focus on for v3. :)

**Comment by JukeJukestar** [comment]
I *may* find the time to go in game to connect some minor haradrim dynasties
(have several dune sea counts descending from an old ruler; make one or more dynasties descend from a bastard branch of another dynasty, such things)

Not gonna touch Umbar though, not without permission from loremasters!

**Comment by jj248** [comment]
Closing as I don't think there's much left to be gained from the issue.
