### ISSUE TITLE
Finalise limitations placed on elven holding tiers

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#507]
Decide on either current limitations or set ratios of tiers.

**Comment by jj248** [comment]
This is almost done - I just need to localise the triggers.  

I have shifted the limitation to be based on the number of elven holdings in your realm.  You need 2 for every stronghold and 4 for every city.  This moves away from limiting this to a limited number locked to each de jure title and should enable taller gameplay.

To account for it being easier to get higher tier holdings, I've reduced the building slot modifiers to -1/+0/+1 vs vanilla holdings for Refuges/Strongholds/Cities.

Will hold off sending to testing until the trigger is localised.

**Comment by jj248** [comment]
Triggers localised and concepts added.  Ready to test.

**Comment by Jauffr** [comment]
![Screenshot 2023-02-21 012243](https://user-images.githubusercontent.com/108106660/220288389-8e04db51-fd3d-4321-a85c-fd9e6b46d208.png)

Testing a custom elf I was able to have a max level elven holding and a second almost max, with only three counties of my culture. As much as I love the idea of filling up Lothlorien with elven holdings and raising the tier of my cities to max all over, I simply think it makes things too simple to upgrade when elves can have multiple elven holdings per county.

I understand that this is a design choice meant to facilitate tall gameplay and the fact is that the system functions as intended and allows that to devestating effect with time. I used cheats to convert things as fast as I did and most players would take far far longer to acomplish what I did here

As a side note. I understand that from a lore perspective it would be rather difficult for the Galathrim to spread the Malorn trees outside Lothlorien. However. Since we are playing with Galadriel and her Ring of power is still working at full force... Perhaps I can persuade you folks to change the Malorn tree holding GFX to be tied to the Galathrim culture instead of being locked to the region of Lothlorien

**Comment by JukeJukestar** [comment]
I agree with Jauffre here, I think having max. 1 holding per county is fine for elves 

- This helps show they are relatively spread out among a county and its not super densely populated
- Rulers in general arent supposed to hold a ton of holdings so having a limited number is good for elves

**Comment by VectorMaximus** [comment]
> I understand that this is a design choice meant to facilitate tall gameplay and the fact is that the system functions as intended and allows that to devestating effect with time. I used cheats to convert things as fast as I did and most players would take far far longer to acomplish what I did here

> You might have to take another look at the refuge level balancing though, since elves will be restricted to a certain number of holdings based on their ammount of counties now

This is exactly why I personally am firmly against doing this. Yes, Elves can theoretically scale very high in time - but that's the exact point, _in time_. I would rather further increase the build times than restrict things if the issue is they ramp up too fast.

**Comment by Jauffr** [comment]
I would wholeheartedly support a penalty to elven buildtime as a remedy to the issue then. I personally do not take issue with how high they can grow their power. After all, I hope to do similar things as a dwarf in future, as it is rather fun. The only thing that makes it a problem, is how fast they ramp up their power. Making things take significantly longer, would help it feel rewarding to take the time to pull it off in the end.

I'd say they should have double the build time of humans

**Comment by savagesach** [comment]
I tested elven modifiers a week or so back when I was playing thranduil and I'm pretty happy with the setup. as I have not seen any complaints about the setup, I think this issue can be closed
