### ISSUE TITLE
Restrict granting of wilderness to vassals

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#522]
Currently vassals are often granted newly colonised wilderness and don't have the income to upgrade to a normal holding.

**Comment by JukeJukestar** [comment]
related to #395 #396

**Comment by jj248** [comment]
Have made it so that wilderness holdings cannot be granted to anyone once colonised.  Moving that specific issue to testing and linking to #523 to note third point above of Juke's when reviewing mechanic as a whole.

**Comment by BriceLeduc** [comment]
![image](https://user-images.githubusercontent.com/98077354/218254116-66ef29d3-f3e4-49bd-bd85-1dde19c7e50a.png)
Wilderness can still be granted to vassals/courtiers through court events

**Comment by Jauffr** [comment]
While players quite clearly not hand out titles that have a settlement building or any of its upgrades, the AI always find a way somehow
![Screenshot 2023-02-22 030308](https://user-images.githubusercontent.com/108106660/220587946-41a3bb75-31fa-4f11-a8d2-a2512d3fac18.png)
![Screenshot 2023-02-22 030342](https://user-images.githubusercontent.com/108106660/220588021-7ba1fcc9-7746-489d-9624-af18f404748a.png)
They will on the first monthly tick hand it over to someone else if they are at their domain limit, otherwise they keep it
![Screenshot 2023-02-22 030640](https://user-images.githubusercontent.com/108106660/220588385-633df142-727c-4e17-9f4c-348ca9494d89.png)
![Screenshot 2023-02-22 025734](https://user-images.githubusercontent.com/108106660/220588391-b57d9a89-3629-422c-b1af-6ce525e3d73c.png)
This leads to almost every single settlement holding in the game being managed by a count that it is handed to instead of the person who founded it. Especially in the case of Lasgalen
![Screenshot 2023-02-22 025953](https://user-images.githubusercontent.com/108106660/220588823-03426d57-5fab-49fa-a1a2-ad95f3e300ca.png)
![Screenshot 2023-02-22 025808](https://user-images.githubusercontent.com/108106660/220588836-d11e0fc5-1602-4a66-9532-9b16486eab63.png)
![Screenshot 2023-02-22 025834](https://user-images.githubusercontent.com/108106660/220588849-8ee14c42-61b4-4c30-9514-e95072097901.png)

**Comment by jj248** [comment]
Agreed - and I had found the way to forbid the AI from handing these out, but it was causing CTDs, so I've disabled for now.  Moving this back to bugs to see if I can resolve.

**Comment by Jauffr** [comment]
This court event still fires for colonies. I am able to hand out my colony as Dol Guldur to a galant champion with event_court_5060
![Screenshot 2023-02-28 004310](https://user-images.githubusercontent.com/108106660/221786881-47ee99a1-79f3-425f-ae85-6f48bd5bd7ff.png)

**Comment by jj248** [comment]
Pushed a fix for the event above.  Also pushing this to testing in general now.  While I haven't been able to explicitly ban the AI from handing out these titles when over domain limit, they should at least be capable of developing them to completion.  So in that regard, I think it's ready to test.

**Comment by jj248** [comment]
Yeh, agree.  Closing.
