### ISSUE TITLE
Imperial unity mechanic

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#524]
Still needs:
•	GUI design
•	Trigger on who has mechanic.
•	Effects and modifiers added.
•	Laws to adjust variables.

**Comment by jj248** [comment]
Have commented this out for now.  We can deal with it as part of a v3.x or v4 update.

**Comment by Jaco-Daan** [comment]
So just looking at this as a potential project to be released for v4 proper (not beta, since that is slated for end of Jan). 

I talked a bit with Vector and apparently this 'mechanic' is mainly (non-canon areas excluded) intended for Medloshukain.

From what I can understand in terms of functionality, it essentially is the 'clan' unity mechanic tied to the Medloshukain title and when it hits 0 'unity' the title would explode.

Wanted to know if there is any more detail on this or whether its something that should potentially be scrapped/pushed to v5

**Comment by Jaco-Daan** [comment]
At the moment this is really more of a concept than anything else. It's also been decided to bench this idea until we go further east, which won't be for another year-ish. Closing this issue until then
