### ISSUE TITLE
New Mechanics : Song Battles

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#660]
The Song Battles mechanics is available to : 
- Elves
- Istari
- Nazgul
- Ringbearers

The initial bets can be : 
- friendly (nothing, unavailable to evil characters)
- for prestige
- for gold

The song battle proceeds in phases (similar to board games).
Song battles where one opponent at least is evil will fire a single combat 2 days after the victory window shows up.

What needs to be checked : 
- [ ] Mechanics runs smoothly
- [ ] The stakes are correctly treated (prestige/gold)
- [ ] Appropriate characters are allowed to take part

**Comment by JukeJukestar** [comment]
Heres what I got from my testing so far:
- Flat 15% chance to become poet isnt a good idea - the decision can just be farmed to have a near guaranteed way of getting it. Maybe have a hidden "song proficiency" stat that has a 50% of leveling up whenever you win - and at a certain ammount you get the poet trait via event. Alternatively, just remove this way of aquiring it
- The middle option during victory "How does it feel to loose little man?" doesnt fit thematically in my opinion, maybe find a better way of mocking them
- The "Draw your weapon fool, lets finish this" option doesnt trigger a duel even though its implied it would
- It feels very weird Galadriel would walk up to a dark sorceress demanding a song battle for some gold or fortune. Maybe we should restrict it just to elves and istari? Its not like there are many sorcerors anyways

Lastly, this is more of a general thing but I dont think this really fits dark characters tonewise. From what I understand this system is a reference to the Silmarillion where some elves duelled people? (Namely there was one between an elf and sauron), but this doesnt really fit the more "down to earth" tone of the third age. Magic in the lotr books always felt like a distant and mystical thing and I think having a "magical duel" option kind of ruins this atmosphere. Even Sarumans and Gandalfs powers were always kept somewhat vague for this reason. And Im not sure this sort of song based magic fits sorcerors very well since their power source is kept very vague, through dark rituals and such

**Comment by RedArkady** [comment]
Hate to piss on anyone's chips, particularly when a lot of work has gone into it, but I'm also a little uncomfortable with the song battles as they stand. I think we only have one example in the lore, and that was in the 'high mythology' First Age and between a Maia and a half-Maia. I'm not sure it suits the more prosaic Third Age, or standard elves. Maybe we restrict it to Maiar, and make it super-rare?

**Comment by JukeJukestar** [comment]
I agree with you, but I would hate it if we restricted it that much since quite a lot fo work went into it. Maybe we could rebrand it to an "elven song duel/ poetry duel" and just remove most references to magic from the loc?

**Comment by BriceLeduc** [comment]
Restricting it Maiar would be pointless, Sauron can't take part.

**Comment by RedArkady** [comment]
> I agree with you, but I would hate it if we restricted it that much since quite a lot fo work went into it. Maybe we could rebrand it to an "elven song duel/ poetry duel" and just remove most references to magic from the loc?

That would be a tidy solution.

**Comment by BriceLeduc** [comment]
I'm sorry but I'm not rewriting the whole thing a month after it's been implemented. We talked about the activity design with Jamie and Vector prior to implementation and everyone agreed on this. Yes it is stretching the lore slightly, but so is having human sorcerers around

**Comment by VectorMaximus** [comment]
Just throwing in my two cents. I think it's fine as-is. As Brice said, its a bit of a stretch but I don't think its massively so - Elves used songs of power, and the world itself was made using them. True, we only have a single actual 'duel' recorded with actual stakes involved, but particularly for more casual contests of elves showing off their Art I imagine they were somewhat more common. If necessary, we can revisit in the future to discuss some _localization_ changes to help make it feel a bit smoother - I think the functional mechanic should remain unchanged.

If the system was also still available to Sorcerers I'd be more amenable to discussing large-scale changes, but as narrowly available as it currently is, I think it works. My only two cents though, thinking about it, Brice - what are the weights to wager different things on the outcome of the songs? Most of the time I'd imagine these were either for nothing or just for prestige, with gold and particularly titles being extraordinarily rare.

**Comment by BriceLeduc** [comment]
It works like board games do : you can choose what to bargain when you pick the interaction. I've never seen the AI pick anything other than friendly or prestige (for evil characters).
The county wager requires you to have neighbouring domain (you can't wager a vassal's title). The conditions are pretty strict, and I could remove the option entirely if it feels too out of place

**Comment by VectorMaximus** [comment]
Makes sense. So long as there isn't consistent bankruptcies or Thranduil gambling away his realm it should be fine then.

**Comment by BriceLeduc** [comment]
You can't wager money you don't have, in CK3 at least

**Comment by VectorMaximus** [comment]
Loan sharks be crying. How will they profit now?

**Comment by BriceLeduc** [comment]
The interaction is apparently throwing CTDs for some people, I can't find anything wrong with the code

**Comment by BriceLeduc** [comment]
I've disabled the option to wager counties, which seems to solve the CTD issue. Ready for testing

**Comment by BriceLeduc** [comment]
Should be working now, ready for testing

**Comment by JukeJukestar** [comment]
My notes on it from further testing:
- The interaction being called "Battle of Songs of Power" feels very clunky, maybe something like "Challenge to Battle of Songs"?
- The tooltip for the interaction should mention the "Athrabeth Lireva" encyclopedia entry somehow so players can take a look at it before the battle and its a bit less hidden
- A tooltip could be displayed giving an indication that the poet trait influences the outcome of the battle ("Your chance of victory is increased by your poet trait" and "Your opponents chance of victory is increased by their poet trait")
- It always says that you lost "due to the contest running out of time". This feels like an error message ("event timed out") and should be reworded if its intentional
- (Personal opinion) I still believe its somewhat immersionbreaking when Dol Guldur challenges an elf to bet their gold on the outcome of a song battle and vice versa.

<details> <summary>The tooltip for not being able to challenge someone is bugged and doesnt display. </summary>

![image](https://user-images.githubusercontent.com/76008882/227028735-a82c375c-b7f7-44c1-b4b3-d4527df8c53d.png)

![image](https://user-images.githubusercontent.com/76008882/227028757-2f930e0b-9b4c-4344-8026-044ee9a9f804.png)

</details>

Thats all for now! Hope some of it is useful to ya, overall working pretty well.

**Comment by BriceLeduc** [comment]
Juke's suggestions integrated in the design, closing the issue
