### ISSUE TITLE
Sorcery review

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#661]
Sorcery activity and learning event chain

What needs to be checked : 

- [ ] spells work correctly
- [ ] sorcery learning is disabled
- [ ] lands protected by one of the Three Rings (Lorien) should not be affected by hostile spells
- [ ] Black Breath spell now applies the illess instead of the modifier

**Comment by JukeJukestar** [comment]
Note that its currently creating a ton of errors due to a lot of events (evil.0122 and such) not being found

**Comment by BriceLeduc** [comment]
OK my bad, apparently the code was functional, I have restored it. Please check that the spells are working

**Comment by BriceLeduc** [comment]
I have restored Ispanets' sorcery code, please test the issues listed in the first post

**Comment by Remerod** [comment]
**Testing spells work correctly**
So I've tested all evil spells with Sauron and Khamul, from what i can see all is working with some exception of not being able to check them (see bellow)

The main issue is that none of the Spells shows any effects on the event that fires, which is very not good, when it's a character modifier it is somewhat traceable but when it affects buildings or other characters it gets very hard to trace (if not near in possible in certain situations).
This clearly needs to be fixed in my opinion. Down bellow are some more precise and potential worse issues

"**Raise dead**" should probably have it's succeeding event tell them that you get an army 
![image](https://user-images.githubusercontent.com/79544635/235260689-30fdff9d-17f3-40b5-b3c4-84bbc370bc0e.png)

Another thing is like here, "**Draw from Dark Vitality**" the sorcery ui told me which character i would steal vitality from, but the event itself don't, which i feel it should do

![image](https://user-images.githubusercontent.com/79544635/235261937-a9dcf8fd-eca5-416f-a0c0-70ed146ccab1.png)

So "**the Black Breath**" window on the sorcery ui kind of explains with flavour, but does not explain what it does with it's modifers on chance of success of what it does, this need to be fixed
![image](https://user-images.githubusercontent.com/79544635/235265852-d091cdfd-d4f8-4dda-bb4f-0949b9eae9ef.png)

And since it has no effect it super hard to check on how it was cast (but it can succeds) so i am very unsure on this one
![image](https://user-images.githubusercontent.com/79544635/235265919-4691b0ad-dd77-479c-a435-858c040cc12c.png)

The "**Cast of Darnkness**" ui explains what it's does but it does not explain if you cast it on yourself or someone else
![image](https://user-images.githubusercontent.com/79544635/235266449-abe7c6cb-4025-4ce3-9d13-95c5872b6a0e.png)

the Cast of Darnkness says it works when cast, but i have no idea how to see it's effect as i don't get any information on where it is cast

I'm moving this to bugs

**Comment by BriceLeduc** [comment]
"Cast the darkness" spell description is pretty clear to me : it affects all rurrounding counties

**Comment by BriceLeduc** [comment]
We have received no question or bug report on the activity, considering things are clear enough without need to further clarify. Closing
