### ISSUE TITLE
Reduce Elven piety and prestige gain, Increase faith conversion and creation cost

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#717]
Because of their long lifespans, elves tend to accrue massive piles of prestige and piety.
It would be nice to do something similar to Elder Kings and reduce the gain of both ressources.
Its also very easy to create a new faith for elves right now - this could make their campaigns a bit lower paced. It would also make their cbs take a little bit longer to get.

This shouldnt be viewed from the angle "why should we reduce prestige and piety generation?", view it instead as "why do elves have insanely massive prestige and piety?"
Immortality in ck3 can be seen as a massive passive buff to both those ressources since unlike gold that is used everywhere, they arent kept on successsion and the main balancing part is that you have to regain them as every ruler, from which they are exempt.

I would propose -25% monthly prestige and piety for elves, we can tweak it later if its too high or low.

==========================================================

So we settled on this:

- [x] 25% -30% for piety and prestige gain
- [x] 100% piety cost for converting to a different faith.
- [x] 50% new faith creation cost
- [x] Disabling the "become a paragon of the faith/the savior" decision

**Comment by JukeJukestar** [comment]
after some discussion this vas viewed as very unpopular in #issue-discussion, closing it

**Comment by JukeJukestar** [comment]
So we settled on 25% -30% for piety and prestige gain

100% piety cost for converting to a different faith.
50% new faith creation cost

as well as disabling the "become a paragon of the faith" decision

**Comment by jj248** [comment]
Ready for tester feedback.

**Comment by Jauffr** [comment]
The cost increase to converting faith and creating new ones is almost completely negligible as a major elf character, however I do not think it should be increased any further, due to how much it would disproportionally affect minor elven characters. The same goes for prestige and faith acquisition. The slower speed is more noticeable and especially on the prestige. After having played multiple elven playthroughs, it functions well, where it is at, however increasing it any further would be detrimental, as elves already need prestige for their buildings costs and piety for monster MAA
![Screenshot 2023-02-28 182904](https://user-images.githubusercontent.com/108106660/222022017-5d71865a-f4e3-48c2-9656-790b3168c2a7.png)
![Screenshot 2023-02-28 182959](https://user-images.githubusercontent.com/108106660/222022019-cfe7f4bb-83c6-45f3-9020-f370c1328009.png)

**Comment by jj248** [comment]
Roger that.  Sounds like we're in a decent place.  We can revisit later if we need to in a separate issue.
