### ISSUE TITLE
Slightly increase Skinchanger inheritance chance

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#730]
Currently, the skinchanger trait usually dies out after the third generation of beornings dies. I think it would be good to increase the oods slightly.
Maybe give the Beorning dynasty a secret inherent bonus as well so it stays in the family, maybe even a bonus for first sons so heirs get it more.

Its a balancing act since we dont want it to become common in Rhovanion through intermarriages, but I do think it would be nice for Beorning players to be able to keep it longer into the game.

**Comment by BriceLeduc** [comment]
we could probably add a head count of skinchangers and dramatically increase the inheritance probability if it drops too low

**Comment by jj248** [comment]
So currently it's done based on Genetic rules, which I quite like... i.e.

```
# If set to yes (no by default), the inheritance will follow the following rules: The trait can be inactive. Children can inherit the trait from both active and inactive parent traits.
											# An active trait is inherited with 100% chance, an inactive trait with a 50% chance. If the trait is successfully inherited from both parents, it becomes active.
											# If it's inherited only from one parent, it's inactive.
```

**Comment by jj248** [comment]
So without a little inbreeding, inheritance chance will be at 50%.

**Comment by Jauffr** [comment]
As things stand. After many observer games where I check back on the Beornings and filter for skin changers worldwide. The trend seems to be 4 of 5 games there will only be two grandchildren of Grimbeorn with Skin changer. and the trait ends with them. This is partly because the Beornings are prone to both not have many children due to the trait negatively affecting fertility and not increasing fertility years. As well as the tendancy for Skin changers to allways be combatants in their liege's armies due to their power. As a result many are maimed and killed outright before they have even a single child. This means that the Beornings have a decent chance of simply dying out due to their own combative nature, while also ensuring that the Skin changers die out even when the Beornings do well. 

I don't think it is necessary to drastically change the chance of the trait being inherited as of now. It could of course have its chances be boosted by 10-15 percent, however there is also a lot of room for more skin changers to be added to the map. That could be a solution if increasing the odds feels to artificial to some. I'd support whatever, so long as it works. Beorn only had two children as of now and one of them, his daughter Sidbeorn "lineofbeorn2a" only had a single child before she became too old for children pre game start.

**Comment by BriceLeduc** [comment]
One thing i can do is to decrease their probability of combat death, to start with

**Comment by BriceLeduc** [comment]
I've decreased their chances to be wounded or killed in battle, please test whether that makes any difference

**Comment by JukeJukestar** [comment]
According to @savagesach s feedback, the trait still needs a buff - it dies out very quickly

**Comment by Foadar** [comment]
Can confirm, still an issue. I did a private run with the Beornings attempting to create Numenorean blood skinchanger supermen, and while the blood of numenor inherited fine, I had to console command skinchanger on all but like 3-4 kids on the 20 or so that ended up being born to Grimbeorn's children (with fertility buffing traits)

**Comment by RedArkady** [comment]
I think this OK now to be honest. Done a few runs where 100 years in there are still 5+ skinchangers, 2+ under the age of 30. Minded to close.

**Comment by jj248** [comment]
OK - closing.  Can keep an eye on it for the future.
