### ISSUE TITLE
Elven courtiers sometimes spawning with ungodly levels of prowess

### ISSUE THREAD

**Issue by hermodr-discord** [jj248/RealmsInExile#769]
Dozens of elven lowborn courtiers worldwide are spawning with insane levels of prowess.
![image_2023-03-13_172209943](https://user-images.githubusercontent.com/83891146/224845902-82d9849d-f108-46a7-8bf6-728fd4ca490e.png)
![image](https://user-images.githubusercontent.com/83891146/224845921-12e57da7-02ce-48b5-9725-f1aaedd035c3.png)
![image](https://user-images.githubusercontent.com/83891146/224845940-aa59b08f-a81c-4590-9698-81ad4a21968c.png)
![image](https://user-images.githubusercontent.com/83891146/224845952-e6e3f45a-7ba9-4246-8d9c-e280fd5df564.png)
![image](https://user-images.githubusercontent.com/83891146/224846082-a46c9f79-f4f0-43fb-881b-966c0f83b613.png)
![image](https://user-images.githubusercontent.com/83891146/224846103-dc53e01a-b50c-4d9b-86bb-9d465e7902d9.png)
![image](https://user-images.githubusercontent.com/83891146/224846134-edd020cb-ae8e-4b57-ad5c-0e7e77606ca6.png)
![image](https://user-images.githubusercontent.com/83891146/224846148-65c98f0f-bb0c-4c29-9d0b-142e74d1379d.png)

**Comment by jj248** [comment]
I believe this was due to an annual event that has a chance for unlanded characters to increase their prowess each year.  Leave the game running long enough and immortal unlanded characters (i.e. elves) see these benefits stack up.  Normally this is countered in vanilla by the penalty to prowess that comes with age define that we've removed.

Therefore, to fix this, I've made it so that prowess can only be increased this way up to a base of 15 for non-immortals and up to 25 for immortals (though at a reduced chance to reflect the slower progression).

Ready to test.

**Comment by BriceLeduc** [comment]
This problem also applies to Orcs, who end up with 50+ prowess, even though they're a lot less justified to having this than Elves
