### ISSUE TITLE
Elves looking old & saggy

### ISSUE THREAD

**Issue by blackbird5598** [jj248/RealmsInExile#779]
![image](https://user-images.githubusercontent.com/125709421/225487070-b6a2e5ef-759a-4b80-bb9f-6f8fba018895.png)

I left my game on observer mode & let it run for a while. Idk why or what had caused it but in the very late game Celeborn & Tari his daughter look like saggy old humans. There were no other elves I could find that looked like this.

**Comment by jj248** [comment]
The thing that sticks out to me is the hybrid culture.  It may be related to #767

**Comment by Remerod** [comment]
wait, you just blocked AI (how am i supposed to test that !? since players are allowed to) :P either way i've never seen any elves diverging or hyberdizing, i've asked other testers if they've seen it but none had from what i heard. 

Not 100% sure of to make sure that the AI won't do this as we can't prompt them into doing it
