### ISSUE TITLE
"Adopt feudal ways through liege" decision bugged for tribal vassals of elves

### ISSUE THREAD

**Issue by Jauffr** [jj248/RealmsInExile#781]
Due to elven government not being either feudal, or clan, this simply does not appear as an option anymore for these characters. Now the poor fey court leofrings are stuck as a tribe. Unable to take advantage of all that juicy development they get from being next to and under galadriel :(

**Comment by jj248** [comment]
Should now be possible.

**Comment by savagesach** [comment]
well the decision is there, but the ai is never going to use it as they'd have to choose to convert to elven religion
![image](https://user-images.githubusercontent.com/86676697/226798072-8a2357c3-5920-4cf1-a098-2c85d371c3e7.png)

**Comment by savagesach** [comment]
it does work as intended though
![image](https://user-images.githubusercontent.com/86676697/226798275-e373c5ce-e2f8-4723-8c5a-f3814a6fe540.png)

**Comment by JukeJukestar** [comment]
That was an Oversight.
- Require the player to have any reformed faith instead of the same liege faith,
- Require absolute tribal authority (as if independent)
- Require level of fame 2 (as if independent)
- Require 5 Development in realm capital (as if independent)

Being an elven vassal shouldnt make feudalizing much easier, they'd probably be relatively hands off instead of actively imposing a feudal system on the locals.

**Comment by Jauffr** [comment]
This works now, however it still requires you to be an organized faith. Also potentially the LOC should be changed, though thats rather minor
![Screenshot 2023-03-22 162102](https://user-images.githubusercontent.com/108106660/227051479-e8bf963c-6ca1-48d7-965f-cb84f1a6ff66.png)

**Comment by BriceLeduc** [comment]
The loc issue has been fixed. The faith restriction is from vanilla and has no reason to be changed.
![image](https://user-images.githubusercontent.com/98077354/229362328-a8eac7aa-7d3a-4987-a8ef-c0ee41e94457.png)
