### ISSUE TITLE
Concept: Bellakarean Turbans

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#797]
## The Idea
Gives Bellakarean characters turbans.
Possibly distinguish between Bellanarud, Bellakaze and Bellakarani so the latter do not use them.
(Bellakarani may not want to wear turbans because they view them as haradrim influence)

There are a variety of turbans from vanilla and Fates of Iberia we could use. The Outhame Turbans also look quite good on them, perhaps we could reuse it

## Why?
Turbans would fit them quite nicely and distinguish them from the Dunedain a bit more, while also making them feel less Byzantine. Now that we have Fates of Iberia, I'm sure some of them would be quite good looking. Niluhin should keep his crown though, and not every character should have a turban, though they should be quite common.

![image](https://user-images.githubusercontent.com/76008882/226742076-d2517d5c-2850-43c0-bff1-605e9541f4ed.png)

**Comment by Remerod** [comment]
Based on the Discord **Bellakarean Turbans** thread it seems this is a good to go. I do think it could be cool to add some colour themes to Bellakar to (i belive that's possible since i've seen jamie done it) 

would be cool if we could make more of their clothes white, gray and maybe an other colour with them maybe having teal, purple and another colour hues for the details

Example:
![image](https://user-images.githubusercontent.com/79544635/226741807-26113149-2e4f-41cf-b46d-fe9cbaa053b0.png)

**Comment by Jaco-Daan** [comment]
Closing this, as turbans have been added
