### ISSUE TITLE
Prevent declaring war on wilderness

### ISSUE THREAD

**Issue by savagesach** [jj248/RealmsInExile#799]
somehow the withered court leofrings in the undeeps managed to declare war on the wilds for a county. I have no idea how it was done.
![image](https://user-images.githubusercontent.com/86676697/226804894-35adf9d7-61cf-4e3e-8069-2c7319c418a3.png)

**Comment by JukeJukestar** [comment]
Theres a random event where a warlike courtier tells you "We should invade someone!" and you can be like "Youre right!" and immediately start a war with a random neighbour. I dont know if this is what caused this, but it might have. No idea about event id tho

**Comment by JukeJukestar** [comment]
Checked every event/ effect that can trigger conquest wars, couldnt find anything, so he probably declared it normally which is odd since he should be blocked from doing that.

**Comment by savagesach** [comment]
I haven't caught any wilderness wars in my observer games recently, but we should double check with other testers before closing the issue

**Comment by Remerod** [comment]
the best way to check this is by observing the wilderness "character" but you cant really do that since you have that wilderness window, is there a way to disable that without removing it for other people? 

![image](https://user-images.githubusercontent.com/79544635/234981425-a40db34a-be74-494e-8f78-59ff3086de69.png)

otherwise i have to agree with Nemcraft, haven't caught any but again, a bit hard to observe to make sure there hasn't been any

**Comment by Remerod** [comment]
So i have been talking with other testers and Jamie and none of us have seen this problem occurring anymore, but i did run a quick observer game for 60 years, no wars where declared (me checking for sieges) on wilderness and i doubled checked all the wilderness stuff that got colonized to make sure it became that way properly

![image](https://user-images.githubusercontent.com/79544635/235259425-40b7f0fe-63ac-4c1c-91bb-e4dba3b52822.png)

So with this i think it's good enough to close! :)
