### ISSUE TITLE
Elves switch governments upon inheritance

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#800]
If you are an Elven vassal of a human and you inherit their titles (which happens if they have no dynastic heirs, as you are usually the eldest vassal around), you also inherit their government.
![image](https://user-images.githubusercontent.com/98077354/226843341-953087f8-0992-44c5-bb5d-4c7a04410e60.png)

**Comment by VectorMaximus** [comment]
Probably could be solved by adding a check to the on_title_gain to swap an elf back to the appropriate government?

**Comment by VectorMaximus** [comment]
From the CK3 wiki on effect, this might be worth looking into more broadly:

> holder = 'Character that should get the title'
change = 'previously created title_and_vassal_change', adds a title change, will not transfer vassals
take_baronies = yes # Optional; if set, will cause baronies to be taken (rather than vassalized) as well if this title is a county
government_base = character # Optional, if the character getting the title was unlanded, their new government will be based on the government of government_base. If no government_base is specified, the government will be based on holder's government.

**Comment by jj248** [comment]
Now force the conversion a day after inheritance.  Ready to test.

**Comment by savagesach** [comment]
I tested it and the conversion happens as intended after inheritance.
![image](https://user-images.githubusercontent.com/86676697/229389889-90af7268-8112-49c7-b98e-f152a22fdf57.png)
![image](https://user-images.githubusercontent.com/86676697/229389898-2d882b1f-cb74-418c-8c81-b9f227366df1.png)
