### ISSUE TITLE
Northron Elective Bugged

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#857]
![image](https://user-images.githubusercontent.com/76008882/235313334-4cf18b95-3843-4c65-9830-47634ab4ff3d.png)

Ya heard the man!

**Comment by Lewa263** [comment]
I uncommented a line that was commented out a few weeks before this issue was made, and it seems to have solved the issue.
Before:
![2024_03_25_1](https://github.com/jj248/RealmsInExile/assets/18605346/e2ebff7d-04cc-4bce-a2cb-64b7f8ee8b77)
After:
![2024_03_25_2](https://github.com/jj248/RealmsInExile/assets/18605346/677526a7-5c21-498d-b4f5-9d029f13458a)

**Comment by Jaco-Daan** [comment]
Seems issue has been fixed, closing
