### ISSUE TITLE
Elven vassals pre-empting refuge upgrade

### ISSUE THREAD

**Issue by BriceLeduc** [jj248/RealmsInExile#895]
There's a lot of complaints about Elven vassals pre-empting the refuge upgrade quota and preventing the players from upgrading theirs. Maybe the upgraded refuge limit should be on a holder base instead of realm base

**Comment by RedArkady** [comment]
Agree, especially as there nowhere in the UI to explain what the problem is.

**Comment by VectorMaximus** [comment]
![image](https://user-images.githubusercontent.com/79318177/236689772-8c8f65f9-a8f2-4dbf-89c7-89b145612084.png)
I've now set it so that it's done on an individual domain basis, instead of the larger realm. I've also set it so that the 'tier' levels _shouldn't_ be pursued by the AI if they are a vassal...

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/b0bc7d9b-0162-4093-8ffc-a3ac01a1f64f)
Vassals upgrading their buildings no longer affects the main liege's ability to upgrade. This works as intended.
