### ISSUE TITLE
Characters holding only colonies (v4-development branch)

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#908]
Sometimes, situations appear where characters only hold colonies, mainly after wars.

We could implement a system where after a war, a check is applied and if the character only holds colonies, they fail and he auto-revokes a county from his vassals. If he doesnt have any, the realm would be disbanded.
If he is a vassal, the titles could instead go to his liege?

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/9ef24035-4504-4a53-8fbf-ea4e0dc68ae6)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/4c5fd999-b829-47ef-a4db-bfea4a1063f6)
Characters that only hold wilderness titles lose their lands as intended. However if they have vassals with land, they still lose all their lands instead of revoking a county from a vassal
![image](https://github.com/jj248/RealmsInExile/assets/86676697/09cd66f8-c7fb-43c0-8c10-77e875707390)

**Comment by JukeJukestar** [comment]
Good spotting! Thats a pretty big issue

**Comment by Jaco-Daan** [comment]
Issue has been fixed, closing
