### ISSUE TITLE
Reunited Kingdom and related decisions (v4-development branch)

### ISSUE THREAD

**Issue by Jaco-Daan** [jj248/RealmsInExile#947]
Making this post off of what Vector's specifications are for creating the Reunited Kingdom and related decisions. 
Also, for reference, the Reunited Kingdom (RK) refers to Arnor and Gondor being united into a single empire.
Vector:
1. If you have the imperial titles of Arnor and Gondor, you can proclaim the Reunited Kingdom, giving it to you as a titular title
2. If you have done (1), then if you *fully control* both Arnor and Gondor, you can *formalize* the Reunited Kingdom, changing it from a titular to a landed title that inherits the dejure and decisions of both, plus unlocking new ones
3. After you've done (2), if you have a high enough prestige/piety/other criteria, you can reunited the Dunedain culturally, swapping from Arnorian/Gondorian to OG Dunedain culture

**Comment by Jaco-Daan** [comment]
More Vector stuff that I'm putting here for reference
Some major decisions I want the RK to have:
1. Province of Fornamar - uniting Angmar and Forochel into a single province
2. Province of Hollin - Eregion
3. Restore the Kingly Priesthood of the Dunedain - create a temporal head of faith title for Erulaitale

Other ones I'm still on the fence on are possible provinces for Lindon and Imladris

**Comment by savagesach** [comment]
I'm looking through this now and aragorn still does not get the empire of arnor

**Comment by savagesach** [comment]
aragorn also still does not get anyone in eriador to vassalize to him

**Comment by Shammien** [comment]
Just adding suggestions for decisions and other flavor for Arnor and RK here, so it does not disappear in the wall of text on Discord. These are lore-friendly mid- to end-game decisions that will add flavor and enhance the player experience. I guess most of them should be approved by Vector and the lead devs. Open for thoughts.

**1 Decision to choose de jure capital of RK**

Requires: 
(1) to complete the RK-chain and reunite Dunedain culturally.
(2) Fully upgraded Annuminas special building. 

Get the choice to move de jure capital to Annuminas for RK. Similar to Gondor's current choice to move it to Osgiliath. We could add different minor bonuses to the ruler, to differentiate between the two. In canon lore, Elessar kept both Annuminas and Minas Tirith as capitals of the RK. He ruled from Annuminas when spending time in the north, and from Minas Tirith when in the south.

**2 Decision to stimulate resettlement of Arnor**

Requires: 
(1) complete the RK-chain and reunited Dunedain culturally. 
(2) Defeat Sauron.
(3) Living Legend
(4) 1500 gold cost
(5) 3000 Prestige cost

The decision encourages the people and offer farmlands in Arnor to the king's subjects in the south. The decision simulate politics that stimulate settlement and immigration to the North Kingdom. Leading to development growth bonuses in all the counties of Arnor for 25 years, as well as a flat increase in 20 development in Annuminas. Lasting some years. 

**3 Decision Establish the Royal Council of Arnor**

(1) complete the RK-chain and reunited Dunedain culturally. 
(2) Defeat Sauron.
(3) Friendly relations with the current ruler of the Shire or (3) Shire vassalized
(4) Holding or vassalized Arthedain, Cardolan and Rhudaur titles.
(5) 3000 Prestige cost

In canon lore: After his accession, Aragorn established a council in Arnor, and in F.A. 13 he chose three Counsellors of the North-kingdom from the people of the Shire and Buckland. These Counsellors were those appointed to the positions of the Than and Mayor of the shire, and the Master of Buckland.

Effect: Decision appoints the three hobbits and current ruler of the three kingdom titles in Arnor as council members. Not sure what the bonuses should be. If Aragorn holds all three kingdom titles, the council will consist of only him and the three hobbits.

**4 Decision to vassalize the other Northern Dunedain and Uialdain rulers of Eriador**

A simple decision click for those of us wanting to play a lore-friendly Aragorn/Eriador. I propose the decision to be given automatically at the start of the campaign, or in 3019 after ascension. Players can opt out if they want.

**5 Decision to use the Elostirion Palantir**

Requires:
Friendly relations or alliance with Cirdan the Shipwright.

Lets the Northern Dunedain ruler use the palantir once every 5 years to gain stress relief and minor times based bonuses.


**Various must-have flavor for Arnor and Northern Dunedain**
 
**A fourth tier of the special building in Annuminas.  "_Ost Elendil Rebuillt_**". Ost Elendil was the seat of power in the former Kingdom of Arnor. It contains the throne room from whence the kings of old would rule their once-grand empire.

The entrance is located on the fortified island of Tyl Annûn overlooking Annúminas from the north. From LOTRO https://lotro-wiki.com/index.php/Ost_Elendil

**Sceptre of Annuminas** Regalia slot item. Should give bonuses to prestige, renown and stewardship. In canon lore, Aragorn was given this sceptre by Elrond after he reclaimed the kingdom and married Arwen. Can be given to him in 3019 if he chooses to ascend the kingship. 

**Need MAA-tradition added to Dunedain culture reunited** Currently reforming RK leads to you losing all your special soldier. Should create a tradition so that the player keeps the gondorian MMA, but also adds these awesome Arnorian MAA:  https://www.reddit.com/r/lotr/comments/ixmkc7/the_arnor_borderguards_artwork_total_war_rise_of/ https://www.artstation.com/artwork/285eOa


Sincerely Arnor simp.

**Comment by savagesach** [comment]
<details>
<summary>Click to expand</summary>

![image](https://github.com/jj248/RealmsInExile/assets/86676697/6d626b08-3c0b-489d-9e3f-88e40b4e4a98)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/4f5d1d21-233a-4899-8d03-3cb9028c9190)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/19590f1b-e3b7-4875-aec2-97cc6a617a4b)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/aa7ffd7b-4aac-45e1-9e07-b0bb0f3a561d)
![image](https://github.com/jj248/RealmsInExile/assets/86676697/929bca2b-5038-4a65-a621-9f9a92a3a7f2)

</details>

These two RK decisions for integrating eregion and enedwaith need more localization and flavor events. Unifying the Dunedain should not give gondorian and arnorian maa due to maa bloat. The Gondorian Renaissance decision should not require killing the druedain and the decision did not register sauron being defeated. Also the peerage tradition was not properly applied, so the bonuses did not work.

**Comment by savagesach** [comment]
Also the scepter of annuminas has not been added yet as an artifact

**Comment by JukeJukestar** [comment]
Note regarding the capital decision: I hope to make a similar framework to the province reclamation decisions for Capital choice, so that Gondor, Arnor, RK, Castamiri Gondor and NiE may choose ones that are appropriate for them through one unified system.

**Comment by jj248** [comment]
From reading on the Discord, I think we're pretty much there with this right @VectorMaximus @Jaco-Daan and @VectorMaximus ?

**Comment by Jaco-Daan** [comment]
Think we still need localisation? @VectorMaximus ?

**Comment by Jaco-Daan** [comment]
Specifically for the Eregion/Enedwaith integration decisions

**Comment by Jaco-Daan** [comment]
This has been finished and no complaints about it, closing
